        ;; _gpx_cursors_tiny.s
        ;;
        ;; Stock cursors as 3-state tiny move streams.
        ;;  state 0: background (pen up / move only)
        ;;  state 2: mask (pen down erase)
        ;;  state 1: foreground (pen down ink)
        ;;
        ;; GENERATED by scripts/assets/gen-partner-cursors.py --
        ;; edit the pictures there, not the bytes here.
        ;;
        ;; Every pixel is covered by exactly one stroke, because the
        ;; Partner shows a sprite by XOR-stroking it and hides it by
        ;; stroking it again. A path that retraced itself would cancel
        ;; the retraced pixels back to the background and break both
        ;; the picture and the show/hide identity. Runs are horizontal
        ;; or vertical only so the EF9367 rasterises them exactly.
        ;;
        ;; FORMAT (tiny bmp_t + hotspot trailer):
        ;;   header (5 bytes):
        ;;     signature = type=10 (tiny), stride nibble=0
        ;;     width, height, size (size = move_count)
        ;;   payload: tiny move bytes (no origin bytes)
        ;;   trailer (2 bytes): hotspot_x, hotspot_y
        ;;
        ;; GPL2 License (see: LICENSE)
        ;; Copyright (C) 2026 Tomaz Stih
        ;;
        ;; 2026-08-26   TS

        .module _gpx_cursors_tiny
        .optsdcc -mz80 sdcccall(1)

        .globl  _gpx_cur_classic_tiny
        .globl  _gpx_cur_std_tiny
        .globl  _gpx_cur_hourglass_tiny
        .globl  _gpx_cur_caret_tiny
        .globl  _gpx_cur_hand_tiny

        .area   _CODE

_gpx_cur_classic_tiny::
        .db     0x20                    ; signature: tiny type=10, stride nibble=0
        .db     0x08                    ; width
        .db     0x0A                    ; height
        .dw     0x0033                  ; payload size (moves only)
        .db     0x19                    ; move 000: color=mask dx=+0 dy=+3
        .db     0x3C                    ; move 001: color=move dx=+1 dy=-3
        .db     0x01                    ; move 002: color=mask dx=+0 dy=+0
        .db     0x28                    ; move 003: color=move dx=+1 dy=+1
        .db     0x01                    ; move 004: color=mask dx=+0 dy=+0
        .db     0x28                    ; move 005: color=move dx=+1 dy=+1
        .db     0x01                    ; move 006: color=mask dx=+0 dy=+0
        .db     0x28                    ; move 007: color=move dx=+1 dy=+1
        .db     0x01                    ; move 008: color=mask dx=+0 dy=+0
        .db     0x6A                    ; move 009: color=move dx=-3 dy=+1
        .db     0x22                    ; move 010: color=move dx=-1 dy=+0
        .db     0x19                    ; move 011: color=mask dx=+0 dy=+3
        .db     0x7C                    ; move 012: color=move dx=+3 dy=-3
        .db     0x40                    ; move 013: color=move dx=+2 dy=+0
        .db     0x01                    ; move 014: color=mask dx=+0 dy=+0
        .db     0x28                    ; move 015: color=move dx=+1 dy=+1
        .db     0x01                    ; move 016: color=mask dx=+0 dy=+0
        .db     0x4A                    ; move 017: color=move dx=-2 dy=+1
        .db     0x21                    ; move 018: color=mask dx=+1 dy=+0
        .db     0x6A                    ; move 019: color=move dx=-3 dy=+1
        .db     0x01                    ; move 020: color=mask dx=+0 dy=+0
        .db     0x60                    ; move 021: color=move dx=+3 dy=+0
        .db     0x09                    ; move 022: color=mask dx=+0 dy=+1
        .db     0x62                    ; move 023: color=move dx=-3 dy=+0
        .db     0x42                    ; move 024: color=move dx=-2 dy=+0
        .db     0x21                    ; move 025: color=mask dx=+1 dy=+0
        .db     0x40                    ; move 026: color=move dx=+2 dy=+0
        .db     0x01                    ; move 027: color=mask dx=+0 dy=+0
        .db     0x28                    ; move 028: color=move dx=+1 dy=+1
        .db     0x01                    ; move 029: color=mask dx=+0 dy=+0
        .db     0x7E                    ; move 030: color=move dx=-3 dy=-3
        .db     0x1C                    ; move 031: color=move dx=+0 dy=-3
        .db     0x14                    ; move 032: color=move dx=+0 dy=-2
        .db     0x98                    ; move 033: color=fore dx=+0 dy=+3
        .db     0x34                    ; move 034: color=move dx=+1 dy=-2
        .db     0x98                    ; move 035: color=fore dx=+0 dy=+3
        .db     0x34                    ; move 036: color=move dx=+1 dy=-2
        .db     0x98                    ; move 037: color=fore dx=+0 dy=+3
        .db     0x34                    ; move 038: color=move dx=+1 dy=-2
        .db     0x88                    ; move 039: color=fore dx=+0 dy=+1
        .db     0x62                    ; move 040: color=move dx=-3 dy=+0
        .db     0x90                    ; move 041: color=fore dx=+0 dy=+2
        .db     0x74                    ; move 042: color=move dx=+3 dy=-2
        .db     0x20                    ; move 043: color=move dx=+1 dy=+0
        .db     0x80                    ; move 044: color=fore dx=+0 dy=+0
        .db     0x6A                    ; move 045: color=move dx=-3 dy=+1
        .db     0x80                    ; move 046: color=fore dx=+0 dy=+0
        .db     0x28                    ; move 047: color=move dx=+1 dy=+1
        .db     0xA0                    ; move 048: color=fore dx=+1 dy=+0
        .db     0x08                    ; move 049: color=move dx=+0 dy=+1
        .db     0x80                    ; move 050: color=fore dx=+0 dy=+0
        .db     0x01                    ; hotspot_x
        .db     0x01                    ; hotspot_y
        ;; 3-state rows: . = bg, m = mask, f = fore
        ;;   00: mm......
        ;;   01: mfm.....
        ;;   02: mffm....
        ;;   03: mfffm...
        ;;   04: mffffm..
        ;;   05: mfffffm.
        ;;   06: mfffmm..
        ;;   07: mfmffm..
        ;;   08: mm.mfm..
        ;;   09: ....m...
        ;; moves: 51
        ;; color pass order: 2 then 1

_gpx_cur_std_tiny::
        .db     0x20                    ; signature: tiny type=10, stride nibble=0
        .db     0x08                    ; width
        .db     0x0A                    ; height
        .dw     0x0032                  ; payload size (moves only)
        .db     0x28                    ; move 000: color=move dx=+1 dy=+1
        .db     0x19                    ; move 001: color=mask dx=+0 dy=+3
        .db     0x34                    ; move 002: color=move dx=+1 dy=-2
        .db     0x19                    ; move 003: color=mask dx=+0 dy=+3
        .db     0x34                    ; move 004: color=move dx=+1 dy=-2
        .db     0x19                    ; move 005: color=mask dx=+0 dy=+3
        .db     0x34                    ; move 006: color=move dx=+1 dy=-2
        .db     0x09                    ; move 007: color=mask dx=+0 dy=+1
        .db     0x62                    ; move 008: color=move dx=-3 dy=+0
        .db     0x11                    ; move 009: color=mask dx=+0 dy=+2
        .db     0x74                    ; move 010: color=move dx=+3 dy=-2
        .db     0x20                    ; move 011: color=move dx=+1 dy=+0
        .db     0x01                    ; move 012: color=mask dx=+0 dy=+0
        .db     0x6A                    ; move 013: color=move dx=-3 dy=+1
        .db     0x01                    ; move 014: color=mask dx=+0 dy=+0
        .db     0x28                    ; move 015: color=move dx=+1 dy=+1
        .db     0x21                    ; move 016: color=mask dx=+1 dy=+0
        .db     0x2A                    ; move 017: color=move dx=-1 dy=+1
        .db     0x21                    ; move 018: color=mask dx=+1 dy=+0
        .db     0x7E                    ; move 019: color=move dx=-3 dy=-3
        .db     0x3E                    ; move 020: color=move dx=-1 dy=-3
        .db     0x14                    ; move 021: color=move dx=+0 dy=-2
        .db     0x98                    ; move 022: color=fore dx=+0 dy=+3
        .db     0x3C                    ; move 023: color=move dx=+1 dy=-3
        .db     0x80                    ; move 024: color=fore dx=+0 dy=+0
        .db     0x28                    ; move 025: color=move dx=+1 dy=+1
        .db     0x80                    ; move 026: color=fore dx=+0 dy=+0
        .db     0x28                    ; move 027: color=move dx=+1 dy=+1
        .db     0x80                    ; move 028: color=fore dx=+0 dy=+0
        .db     0x28                    ; move 029: color=move dx=+1 dy=+1
        .db     0x80                    ; move 030: color=fore dx=+0 dy=+0
        .db     0x6A                    ; move 031: color=move dx=-3 dy=+1
        .db     0x22                    ; move 032: color=move dx=-1 dy=+0
        .db     0x98                    ; move 033: color=fore dx=+0 dy=+3
        .db     0x7C                    ; move 034: color=move dx=+3 dy=-3
        .db     0x40                    ; move 035: color=move dx=+2 dy=+0
        .db     0x80                    ; move 036: color=fore dx=+0 dy=+0
        .db     0x28                    ; move 037: color=move dx=+1 dy=+1
        .db     0x80                    ; move 038: color=fore dx=+0 dy=+0
        .db     0x4A                    ; move 039: color=move dx=-2 dy=+1
        .db     0xA0                    ; move 040: color=fore dx=+1 dy=+0
        .db     0x6A                    ; move 041: color=move dx=-3 dy=+1
        .db     0x88                    ; move 042: color=fore dx=+0 dy=+1
        .db     0x6C                    ; move 043: color=move dx=+3 dy=-1
        .db     0x88                    ; move 044: color=fore dx=+0 dy=+1
        .db     0x62                    ; move 045: color=move dx=-3 dy=+0
        .db     0x22                    ; move 046: color=move dx=-1 dy=+0
        .db     0x80                    ; move 047: color=fore dx=+0 dy=+0
        .db     0x48                    ; move 048: color=move dx=+2 dy=+1
        .db     0xA0                    ; move 049: color=fore dx=+1 dy=+0
        .db     0x01                    ; hotspot_x
        .db     0x01                    ; hotspot_y
        ;; 3-state rows: . = bg, m = mask, f = fore
        ;;   00: ff......
        ;;   01: fmf.....
        ;;   02: fmmf....
        ;;   03: fmmmf...
        ;;   04: fmmmmf..
        ;;   05: fmmmmmf.
        ;;   06: fmmmff..
        ;;   07: fmfmmf..
        ;;   08: .ffmmf..
        ;;   09: ...ff...
        ;; moves: 50
        ;; color pass order: 2 then 1

_gpx_cur_hourglass_tiny::
        .db     0x20                    ; signature: tiny type=10, stride nibble=0
        .db     0x08                    ; width
        .db     0x0A                    ; height
        .dw     0x0035                  ; payload size (moves only)
        .db     0x48                    ; move 000: color=move dx=+2 dy=+1
        .db     0x41                    ; move 001: color=mask dx=+2 dy=+0
        .db     0x4A                    ; move 002: color=move dx=-2 dy=+1
        .db     0x01                    ; move 003: color=mask dx=+0 dy=+0
        .db     0x40                    ; move 004: color=move dx=+2 dy=+0
        .db     0x01                    ; move 005: color=mask dx=+0 dy=+0
        .db     0x2A                    ; move 006: color=move dx=-1 dy=+1
        .db     0x01                    ; move 007: color=mask dx=+0 dy=+0
        .db     0x10                    ; move 008: color=move dx=+0 dy=+2
        .db     0x09                    ; move 009: color=mask dx=+0 dy=+1
        .db     0x22                    ; move 010: color=move dx=-1 dy=+0
        .db     0x09                    ; move 011: color=mask dx=+0 dy=+1
        .db     0x4C                    ; move 012: color=move dx=+2 dy=-1
        .db     0x09                    ; move 013: color=mask dx=+0 dy=+1
        .db     0x7E                    ; move 014: color=move dx=-3 dy=-3
        .db     0x3E                    ; move 015: color=move dx=-1 dy=-3
        .db     0x0C                    ; move 016: color=move dx=+0 dy=-1
        .db     0xE0                    ; move 017: color=fore dx=+3 dy=+0
        .db     0x20                    ; move 018: color=move dx=+1 dy=+0
        .db     0xC0                    ; move 019: color=fore dx=+2 dy=+0
        .db     0x6A                    ; move 020: color=move dx=-3 dy=+1
        .db     0x42                    ; move 021: color=move dx=-2 dy=+0
        .db     0x88                    ; move 022: color=fore dx=+0 dy=+1
        .db     0x6C                    ; move 023: color=move dx=+3 dy=-1
        .db     0x20                    ; move 024: color=move dx=+1 dy=+0
        .db     0x88                    ; move 025: color=fore dx=+0 dy=+1
        .db     0x42                    ; move 026: color=move dx=-2 dy=+0
        .db     0x80                    ; move 027: color=fore dx=+0 dy=+0
        .db     0x2A                    ; move 028: color=move dx=-1 dy=+1
        .db     0x80                    ; move 029: color=fore dx=+0 dy=+0
        .db     0x40                    ; move 030: color=move dx=+2 dy=+0
        .db     0x80                    ; move 031: color=fore dx=+0 dy=+0
        .db     0x2A                    ; move 032: color=move dx=-1 dy=+1
        .db     0x80                    ; move 033: color=fore dx=+0 dy=+0
        .db     0x2A                    ; move 034: color=move dx=-1 dy=+1
        .db     0x80                    ; move 035: color=fore dx=+0 dy=+0
        .db     0x40                    ; move 036: color=move dx=+2 dy=+0
        .db     0x80                    ; move 037: color=fore dx=+0 dy=+0
        .db     0x6A                    ; move 038: color=move dx=-3 dy=+1
        .db     0x90                    ; move 039: color=fore dx=+0 dy=+2
        .db     0x74                    ; move 040: color=move dx=+3 dy=-2
        .db     0x20                    ; move 041: color=move dx=+1 dy=+0
        .db     0x90                    ; move 042: color=fore dx=+0 dy=+2
        .db     0x4E                    ; move 043: color=move dx=-2 dy=-1
        .db     0x88                    ; move 044: color=fore dx=+0 dy=+1
        .db     0x62                    ; move 045: color=move dx=-3 dy=+0
        .db     0x80                    ; move 046: color=fore dx=+0 dy=+0
        .db     0x40                    ; move 047: color=move dx=+2 dy=+0
        .db     0x80                    ; move 048: color=fore dx=+0 dy=+0
        .db     0x40                    ; move 049: color=move dx=+2 dy=+0
        .db     0x80                    ; move 050: color=fore dx=+0 dy=+0
        .db     0x40                    ; move 051: color=move dx=+2 dy=+0
        .db     0x80                    ; move 052: color=fore dx=+0 dy=+0
        .db     0x03                    ; hotspot_x
        .db     0x04                    ; hotspot_y
        ;; 3-state rows: . = bg, m = mask, f = fore
        ;;   00: fffffff.
        ;;   01: .fmmmf..
        ;;   02: .fmfmf..
        ;;   03: ..fmf...
        ;;   04: ...f....
        ;;   05: ..fmf...
        ;;   06: .fmmmf..
        ;;   07: .fmfmf..
        ;;   08: fffffff.
        ;;   09: ........
        ;; moves: 53
        ;; color pass order: 2 then 1

_gpx_cur_caret_tiny::
        .db     0x20                    ; signature: tiny type=10, stride nibble=0
        .db     0x08                    ; width
        .db     0x0A                    ; height
        .dw     0x002B                  ; payload size (moves only)
        .db     0x28                    ; move 000: color=move dx=+1 dy=+1
        .db     0x01                    ; move 001: color=mask dx=+0 dy=+0
        .db     0x40                    ; move 002: color=move dx=+2 dy=+0
        .db     0x01                    ; move 003: color=mask dx=+0 dy=+0
        .db     0x2A                    ; move 004: color=move dx=-1 dy=+1
        .db     0x19                    ; move 005: color=mask dx=+0 dy=+3
        .db     0x08                    ; move 006: color=move dx=+0 dy=+1
        .db     0x09                    ; move 007: color=mask dx=+0 dy=+1
        .db     0x2A                    ; move 008: color=move dx=-1 dy=+1
        .db     0x01                    ; move 009: color=mask dx=+0 dy=+0
        .db     0x40                    ; move 010: color=move dx=+2 dy=+0
        .db     0x01                    ; move 011: color=mask dx=+0 dy=+0
        .db     0x7E                    ; move 012: color=move dx=-3 dy=-3
        .db     0x1C                    ; move 013: color=move dx=+0 dy=-3
        .db     0x14                    ; move 014: color=move dx=+0 dy=-2
        .db     0x90                    ; move 015: color=fore dx=+0 dy=+2
        .db     0x34                    ; move 016: color=move dx=+1 dy=-2
        .db     0x80                    ; move 017: color=fore dx=+0 dy=+0
        .db     0x40                    ; move 018: color=move dx=+2 dy=+0
        .db     0xA0                    ; move 019: color=fore dx=+1 dy=+0
        .db     0x4A                    ; move 020: color=move dx=-2 dy=+1
        .db     0x80                    ; move 021: color=fore dx=+0 dy=+0
        .db     0x40                    ; move 022: color=move dx=+2 dy=+0
        .db     0x88                    ; move 023: color=fore dx=+0 dy=+1
        .db     0x62                    ; move 024: color=move dx=-3 dy=+0
        .db     0x98                    ; move 025: color=fore dx=+0 dy=+3
        .db     0x5C                    ; move 026: color=move dx=+2 dy=-3
        .db     0x98                    ; move 027: color=fore dx=+0 dy=+3
        .db     0x4A                    ; move 028: color=move dx=-2 dy=+1
        .db     0x88                    ; move 029: color=fore dx=+0 dy=+1
        .db     0x4C                    ; move 030: color=move dx=+2 dy=-1
        .db     0x88                    ; move 031: color=fore dx=+0 dy=+1
        .db     0x62                    ; move 032: color=move dx=-3 dy=+0
        .db     0x90                    ; move 033: color=fore dx=+0 dy=+2
        .db     0x74                    ; move 034: color=move dx=+3 dy=-2
        .db     0x20                    ; move 035: color=move dx=+1 dy=+0
        .db     0x90                    ; move 036: color=fore dx=+0 dy=+2
        .db     0x4E                    ; move 037: color=move dx=-2 dy=-1
        .db     0x80                    ; move 038: color=fore dx=+0 dy=+0
        .db     0x2A                    ; move 039: color=move dx=-1 dy=+1
        .db     0x80                    ; move 040: color=fore dx=+0 dy=+0
        .db     0x40                    ; move 041: color=move dx=+2 dy=+0
        .db     0x80                    ; move 042: color=fore dx=+0 dy=+0
        .db     0x01                    ; hotspot_x
        .db     0x07                    ; hotspot_y
        ;; 3-state rows: . = bg, m = mask, f = fore
        ;;   00: ff.ff...
        ;;   01: fmfmf...
        ;;   02: ffmff...
        ;;   03: .fmf....
        ;;   04: .fmf....
        ;;   05: .fmf....
        ;;   06: .fmf....
        ;;   07: ffmff...
        ;;   08: fmfmf...
        ;;   09: ff.ff...
        ;; moves: 43
        ;; color pass order: 2 then 1

_gpx_cur_hand_tiny::
        .db     0x20                    ; signature: tiny type=10, stride nibble=0
        .db     0x08                    ; width
        .db     0x0A                    ; height
        .dw     0x0031                  ; payload size (moves only)
        .db     0x48                    ; move 000: color=move dx=+2 dy=+1
        .db     0x19                    ; move 001: color=mask dx=+0 dy=+3
        .db     0x4C                    ; move 002: color=move dx=+2 dy=-1
        .db     0x19                    ; move 003: color=mask dx=+0 dy=+3
        .db     0x54                    ; move 004: color=move dx=+2 dy=-2
        .db     0x19                    ; move 005: color=mask dx=+0 dy=+3
        .db     0x76                    ; move 006: color=move dx=-3 dy=-2
        .db     0x42                    ; move 007: color=move dx=-2 dy=+0
        .db     0x11                    ; move 008: color=mask dx=+0 dy=+2
        .db     0x34                    ; move 009: color=move dx=+1 dy=-2
        .db     0x19                    ; move 010: color=mask dx=+0 dy=+3
        .db     0x34                    ; move 011: color=move dx=+1 dy=-2
        .db     0x11                    ; move 012: color=mask dx=+0 dy=+2
        .db     0x54                    ; move 013: color=move dx=+2 dy=-2
        .db     0x11                    ; move 014: color=mask dx=+0 dy=+2
        .db     0x2E                    ; move 015: color=move dx=-1 dy=-1
        .db     0x09                    ; move 016: color=mask dx=+0 dy=+1
        .db     0x5E                    ; move 017: color=move dx=-2 dy=-3
        .db     0x1C                    ; move 018: color=move dx=+0 dy=-3
        .db     0x14                    ; move 019: color=move dx=+0 dy=-2
        .db     0x80                    ; move 020: color=fore dx=+0 dy=+0
        .db     0x2A                    ; move 021: color=move dx=-1 dy=+1
        .db     0x98                    ; move 022: color=fore dx=+0 dy=+3
        .db     0x5C                    ; move 023: color=move dx=+2 dy=-3
        .db     0x98                    ; move 024: color=fore dx=+0 dy=+3
        .db     0x34                    ; move 025: color=move dx=+1 dy=-2
        .db     0xA0                    ; move 026: color=fore dx=+1 dy=+0
        .db     0x08                    ; move 027: color=move dx=+0 dy=+1
        .db     0x90                    ; move 028: color=fore dx=+0 dy=+2
        .db     0x34                    ; move 029: color=move dx=+1 dy=-2
        .db     0x80                    ; move 030: color=fore dx=+0 dy=+0
        .db     0x6A                    ; move 031: color=move dx=-3 dy=+1
        .db     0x62                    ; move 032: color=move dx=-3 dy=+0
        .db     0x98                    ; move 033: color=fore dx=+0 dy=+3
        .db     0x7C                    ; move 034: color=move dx=+3 dy=-3
        .db     0x60                    ; move 035: color=move dx=+3 dy=+0
        .db     0x20                    ; move 036: color=move dx=+1 dy=+0
        .db     0x98                    ; move 037: color=fore dx=+0 dy=+3
        .db     0x76                    ; move 038: color=move dx=-3 dy=-2
        .db     0x22                    ; move 039: color=move dx=-1 dy=+0
        .db     0x80                    ; move 040: color=fore dx=+0 dy=+0
        .db     0x5A                    ; move 041: color=move dx=-2 dy=+3
        .db     0x80                    ; move 042: color=fore dx=+0 dy=+0
        .db     0x60                    ; move 043: color=move dx=+3 dy=+0
        .db     0x40                    ; move 044: color=move dx=+2 dy=+0
        .db     0x80                    ; move 045: color=fore dx=+0 dy=+0
        .db     0x6A                    ; move 046: color=move dx=-3 dy=+1
        .db     0x22                    ; move 047: color=move dx=-1 dy=+0
        .db     0xE0                    ; move 048: color=fore dx=+3 dy=+0
        .db     0x02                    ; hotspot_x
        .db     0x00                    ; hotspot_y
        ;; 3-state rows: . = bg, m = mask, f = fore
        ;;   00: ..f.....
        ;;   01: .fmf....
        ;;   02: .fmfff..
        ;;   03: .fmfmff.
        ;;   04: ffmfmfmf
        ;;   05: fmmfmfmf
        ;;   06: fmmmmmmf
        ;;   07: fmmmmmmf
        ;;   08: .fmmmmf.
        ;;   09: ..ffff..
        ;; moves: 49
        ;; color pass order: 2 then 1
