#!/usr/bin/env python3
"""Generate src/partner/_gpx_cursors_tiny.s from the pictures below.

The Partner shows a sprite by XOR-stroking it and hides it by stroking it
again (src/partner/gpx_show_sprite.s), so a stock cursor is only correct if
every pixel of it is plotted exactly ONCE. A path that retraces itself -- the
natural way to fill a shape -- cancels those pixels back to the background
under XOR and the cursor falls apart.

So each picture is covered here by disjoint horizontal and vertical runs,
joined by pen-up moves. Runs are at most four pixels because the move byte
carries only two bits of delta per axis, and they are never slanted so the
EF9367 vector generator rasterises them exactly.

Regenerate with:  python3 scripts/assets/gen-partner-cursors.py
"""

import os

# . = background, m = mask (drawn in CO_BACK), f = foreground (CO_FORE)
CURSORS = {
    "classic":   ["mm......", "mfm.....", "mffm....", "mfffm...", "mffffm..",
                  "mfffffm.", "mfffmm..", "mfmffm..", "mm.mfm..", "....m..."],
    "std":       ["ff......", "fmf.....", "fmmf....", "fmmmf...", "fmmmmf..",
                  "fmmmmmf.", "fmmmff..", "fmfmmf..", ".ffmmf..", "...ff..."],
    "hourglass": ["fffffff.", ".fmmmf..", ".fmfmf..", "..fmf...", "...f....",
                  "..fmf...", ".fmmmf..", ".fmfmf..", "fffffff.", "........"],
    "caret":     ["ff.ff...", "fmfmf...", "ffmff...", ".fmf....", ".fmf....",
                  ".fmf....", ".fmf....", "ffmff...", "fmfmf...", "ff.ff..."],
    "hand":      ["..f.....", ".fmf....", ".fmfff..", ".fmfmff.", "ffmfmfmf",
                  "fmmfmfmf", "fmmmmmmf", "fmmmmmmf", ".fmmmmf.", "..ffff.."],
}
HOTSPOT = {"classic": (1, 1), "std": (1, 1), "hourglass": (3, 4),
           "caret": (1, 7), "hand": (2, 0)}
ORDER = ("classic", "std", "hourglass", "caret", "hand")

MAXD = 3                      # each delta field is two bits
COMMENT_COL = 41              # docs/standards/ASSEMBLY_STYLE_GUIDE.md


def runs_for(rows, ch):
    """Cover every `ch` pixel exactly once with straight runs of <= 4 px."""
    todo = {(x, y) for y, r in enumerate(rows)
            for x, c in enumerate(r) if c == ch}
    out = []
    while todo:
        x0, y0 = min(todo, key=lambda p: (p[1], p[0]))
        best = (0, 1, 0)
        for dx, dy in ((1, 0), (0, 1)):
            n = 0
            while n <= MAXD and (x0 + dx * n, y0 + dy * n) in todo:
                n += 1
            if n > best[0]:
                best = (n, dx, dy)
        n, dx, dy = best
        pts = [(x0 + dx * i, y0 + dy * i) for i in range(n)]
        todo.difference_update(pts)
        out.append((pts[0], pts[-1]))
    return out


def encode(dx, dy, cc):
    mv = (abs(dx) << 5) | (abs(dy) << 3)
    if dx < 0:
        mv |= 0x02
    if dy < 0:
        mv |= 0x04
    if cc == 1:
        mv |= 0x80
    elif cc == 2:
        mv |= 0x01
    return mv


def stream(rows):
    """Mask runs first, then foreground, so ink wins on the copy path."""
    work = ([(r, 2) for r in runs_for(rows, "m")]
            + [(r, 1) for r in runs_for(rows, "f")])
    moves, notes, cur = [], [], (0, 0)
    for (a, b), cc in work:
        while cur != a:
            dx = max(-MAXD, min(MAXD, a[0] - cur[0]))
            dy = max(-MAXD, min(MAXD, a[1] - cur[1]))
            moves.append(encode(dx, dy, 0))
            notes.append(f"color=move dx={dx:+d} dy={dy:+d}")
            cur = (cur[0] + dx, cur[1] + dy)
        dx, dy = b[0] - a[0], b[1] - a[1]
        moves.append(encode(dx, dy, cc))
        notes.append(f"color={'fore' if cc == 1 else 'mask'} "
                     f"dx={dx:+d} dy={dy:+d}")
        cur = b
    return moves, notes


def row(text, comment):
    pad = max(1, COMMENT_COL - 1 - len(text))
    return f"{text}{' ' * pad}; {comment}\n"


def main():
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    out = [
        "        ;; _gpx_cursors_tiny.s\n",
        "        ;;\n",
        "        ;; Stock cursors as 3-state tiny move streams.\n",
        "        ;;  state 0: background (pen up / move only)\n",
        "        ;;  state 2: mask (pen down erase)\n",
        "        ;;  state 1: foreground (pen down ink)\n",
        "        ;;\n",
        "        ;; GENERATED by scripts/assets/gen-partner-cursors.py --\n",
        "        ;; edit the pictures there, not the bytes here.\n",
        "        ;;\n",
        "        ;; Every pixel is covered by exactly one stroke, because the\n",
        "        ;; Partner shows a sprite by XOR-stroking it and hides it by\n",
        "        ;; stroking it again. A path that retraced itself would cancel\n",
        "        ;; the retraced pixels back to the background and break both\n",
        "        ;; the picture and the show/hide identity. Runs are horizontal\n",
        "        ;; or vertical only so the EF9367 rasterises them exactly.\n",
        "        ;;\n",
        "        ;; FORMAT (tiny bmp_t + hotspot trailer):\n",
        "        ;;   header (5 bytes):\n",
        "        ;;     signature = type=10 (tiny), stride nibble=0\n",
        "        ;;     width, height, size (size = move_count)\n",
        "        ;;   payload: tiny move bytes (no origin bytes)\n",
        "        ;;   trailer (2 bytes): hotspot_x, hotspot_y\n",
        "        ;;\n",
        "        ;; GPL2 License (see: LICENSE)\n",
        "        ;; Copyright (C) 2026 Tomaz Stih\n",
        "        ;;\n",
        "        ;; 2026-08-26   TS\n",
        "\n",
        "        .module _gpx_cursors_tiny\n",
        "        .optsdcc -mz80 sdcccall(1)\n",
        "\n",
    ]
    for n in ORDER:
        out.append(f"        .globl  _gpx_cur_{n}_tiny\n")
    out += ["\n", "        .area   _CODE\n"]

    for n in ORDER:
        rows = CURSORS[n]
        moves, notes = stream(rows)
        hx, hy = HOTSPOT[n]
        out.append("\n")
        out.append(f"_gpx_cur_{n}_tiny::\n")
        out.append(row("        .db     0x20",
                       "signature: tiny type=10, stride nibble=0"))
        out.append(row(f"        .db     0x{len(rows[0]):02X}", "width"))
        out.append(row(f"        .db     0x{len(rows):02X}", "height"))
        out.append(row(f"        .dw     0x{len(moves):04X}",
                       "payload size (moves only)"))
        for i, (mv, note) in enumerate(zip(moves, notes)):
            out.append(row(f"        .db     0x{mv:02X}",
                           f"move {i:03d}: {note}"))
        out.append(row(f"        .db     0x{hx:02X}", "hotspot_x"))
        out.append(row(f"        .db     0x{hy:02X}", "hotspot_y"))
        out.append("        ;; 3-state rows: . = bg, m = mask, f = fore\n")
        for i, r in enumerate(rows):
            out.append(f"        ;;   {i:02d}: {r}\n")
        out.append(f"        ;; moves: {len(moves)}\n")
        out.append("        ;; color pass order: 2 then 1\n")

    path = os.path.join(root, "src", "partner", "_gpx_cursors_tiny.s")
    open(path, "w").write("".join(out))
    print(f"wrote {os.path.relpath(path, root)}")
    for n in ORDER:
        print(f"  {n:10s} {len(stream(CURSORS[n])[0])} moves")


if __name__ == "__main__":
    main()
